packages:
  - 'packages/*'

catalog:
  postcss: 8.5.3
  vue: 3.5.13
  vite: 6.2.1
  typescript: 5.8.2
  '@types/node': 22.13.10
  '@vitejs/plugin-vue': 5.2.1
  terser: 5.39.0

  '@laynezh/vite-plugin-lib-assets': 1.1.0
  vite-plugin-css-injected-by-js: 3.5.2
  vite-plugin-dts: 4.5.3
