packages:
  - 'packages/*'

catalog:
  postcss: 8.5.3
  vue: 3.5.14
  vite: 6.3.5
  typescript: 5.8.3
  '@types/node': 22.15.18
  '@vitejs/plugin-vue': 5.2.4
  terser: 5.39.2
  '@laynezh/vite-plugin-lib-assets': 1.1.0
  vite-plugin-css-injected-by-js: 3.5.2
  vite-plugin-dts: 4.5.4
